<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Artikel_model extends CI_Model
{

    public $table = 'artikel';
    public $id = 'id_artikel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_artikel', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('content', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_artikel', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('content', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function jumlah_data()
    {
        return $this->db->get('artikel')->num_rows();
    }
    function data($number,$offset){
        $this->db->where('aktif',1);
        return $query = $this->db->get('artikel',$number,$offset)->result();       
    }

    public function aktif($id)
    {
        $this->db->set('aktif',1);
        $this->db->where('id_artikel',$id);
        $this->db->update('artikel');
    } 

    public function nonaktif($id)
    {
        $this->db->set('aktif',0);
        $this->db->where('id_artikel',$id);
        $this->db->update('artikel');
    }

}

/* End of file Artikel_model.php */
/* Location: ./application/models/Artikel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-22 08:11:28 */
/* http://harviacode.com */